# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{g5_page_view}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["G5"]
  s.date = %q{2011-01-28}
  s.description = %q{Model for storage of page view details}
  s.email = %q{engineering@g5platform.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "g5_page_view.gemspec",
    "lib/g5_page_view.rb",
    "lib/page_view/campaign.rb",
    "lib/page_view/page_view.rb",
    "lib/page_view/search_engine.rb",
    "lib/page_view/traffic_attribution_factory.rb",
    "mongoid.yml",
    "spec/campaign_spec.rb",
    "spec/page_view_spec.rb",
    "spec/search_engine.rb",
    "spec/spec_helper.rb",
    "spec/traffic_attribution_factory_spec.rb"
  ]
  s.homepage = %q{http://github.com/steveburkett/g5_page_view}
  s.licenses = ["none"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{G5 page view}
  s.test_files = [
    "spec/campaign_spec.rb",
    "spec/page_view_spec.rb",
    "spec/search_engine.rb",
    "spec/spec_helper.rb",
    "spec/traffic_attribution_factory_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, [">= 0"])
      s.add_dependency(%q<bson_ext>, ["~> 1.1"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 0"])
    s.add_dependency(%q<bson_ext>, ["~> 1.1"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

