defaults: &defaults
  nodes: ['localhost:27017']

production:
  database: 'gts_production'
  nodes: ['tm26-s00225:27017', 'tm26-s00247:27017', 'tm26-s00186:27017']
  name: 'gts_replica'
  <<: *defaults
  
development:
  database: 'gts_development'
  <<: *defaults
  
test:
  database: 'gts_test'
  <<: *defaults

